version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@brainhubeu/react-carousel"
    versions:
    - "> 1.13.19"
  - dependency-name: "@brainhubeu/react-carousel"
    versions:
    - "> 1.13.23"
  - dependency-name: slug
    versions:
    - "> 2.1.1"
  - dependency-name: react-hook-form
    versions:
    - 6.14.2
    - 6.15.0
    - 6.15.1
    - 6.15.3
    - 6.15.4
    - 7.0.0
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.0.7
    - 7.1.0
    - 7.2.1
    - 7.2.3
    - 7.3.3
    - 7.3.4
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.10
    - 2.32.11
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.6
    - 2.32.9
    - 3.2.0
    - 3.2.1
    - 3.3.1
  - dependency-name: react-use
    versions:
    - 15.3.8
    - 17.0.1
    - 17.1.0
    - 17.1.1
    - 17.2.1
    - 17.2.3
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.24.0
  - dependency-name: babel-preset-gatsby
    versions:
    - 1.0.0
    - 1.1.0
    - 1.2.0
    - 1.3.0
  - dependency-name: gatsby-plugin-google-analytics
    versions:
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 2.11.0
    - 2.12.0
    - 3.2.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.10.0
    - 2.11.0
    - 2.11.1
    - 3.2.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 3.2.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.10.0
    - 3.9.0
    - 4.2.0
  - dependency-name: gatsby-transformer-remark
    versions:
    - 3.2.0
  - dependency-name: gatsby-plugin-google-tagmanager
    versions:
    - 3.2.0
  - dependency-name: gatsby-plugin-gdpr-cookies
    versions:
    - 1.0.13
    - 1.0.14
  - dependency-name: react-select
    versions:
    - 4.2.0
    - 4.2.1
  - dependency-name: is-mobile
    versions:
    - 3.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: bl
    versions:
    - 1.2.3
  - dependency-name: react
    versions:
    - 16.14.0
  - dependency-name: object-path
    versions:
    - 0.11.5
  - dependency-name: potrace
    versions:
    - 2.1.8
  - dependency-name: react-helmet
    versions:
    - 6.1.0
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  - dependency-name: dot-prop
    versions:
    - 4.2.1
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
