---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/5e3f397fe32af10019202ebc/webhook/forestry
sections:
- type: heading
  label: Pages
- type: document
  path: src/pages/index.md
  label: Accueil
- type: document
  path: src/pages/catalogue.md
  label: Catalogue
- type: document
  path: src/pages/artists.md
  label: Artistes
- type: document
  path: src/pages/actualites.md
  label: Actualités
- type: document
  path: src/pages/le-lieu.md
  label: Le Lieu
- type: directory
  path: src/pages/about
  label: Prestations
  create: all
  match: "**/*"
  templates:
  - about
- type: heading
  label: Bibliothèques
- type: directory
  path: src/pages/artists
  label: Artistes
  create: all
  match: "**/*"
  templates:
  - artist
- type: heading
  label: Composants
- type: document
  path: src/data/reinsurance.json
  label: Réassurance
  match: "**/*"
- type: heading
  label: Configuration
- type: document
  path: site-metadata.json
  label: Informations
  templates:
  - config
upload_dir: static/forestry
public_path: "/forestry"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
