---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/5e3f397fe32af10019202ebc/webhook/forestry
sections:
- type: document
  path: src/pages/index.md
  label: Accueil
- type: directory
  path: src/pages/artists
  label: Artistes
  create: all
  match: "**/*"
  templates:
  - artist
- type: document
  path: src/pages/about.md
  label: À propos
- type: document
  path: src/pages/contact.md
  label: Contact
- type: document
  path: site-metadata.json
  label: Informations
  templates:
  - config
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: npm run forestry:preview
