name: Gulp build and commit updated static

on:
  push:
    branches: [ master ]

jobs:
  gulp-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: sudo apt-get install cmake autoconf automake libtool nasm make pkg-config git
    - name: Build static with Gulp
      uses: elstudio/actions-js-build/build@v2
    - name: Commit changes
      uses: elstudio/actions-js-build/commit@v3
      with:
        commitMessage: Update from Gulp - Updated static folder
