name: Build and publish

on:
  push:
    branches: [ master ]

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: ./.github/scripts/setup.sh
    - run: ./.github/scripts/build_static.sh
    - run: ./.github/scripts/build_publish.sh
